version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: pokemon_web
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql
      && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: pokemon_db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
